### ISSUE TITLE
Practice 4 feedback

### ISSUE THREAD

**Issue by Karljohan99** [raunoraa/autoware_mini_practice_solutions#2]
Issues in `lanelet2_global_planner.py`:
1. ~You haven't completed task 5. When I put the goalpoint where the purple arrow is then the global path is still drawn to the end of the lanelet. The global path should end exactly at the goal point.~
   <img src="https://github.com/user-attachments/assets/4b6bb176-adf4-4668-a6e3-0cbd1022ba76" width=50% height=50%>
   EDIT: I guess your solution satisfies idea 1 in the task, but I still recommend to implement at least idea 2, because later it can be really inconvenient if the global path always ends at the end of a lanelet.
2. Move the loading of lanelet2 map below the assignment of parameters. The code structure is a little better that way.
    https://github.com/raunoraa/autoware_mini_practice_solutions/blob/9e1c00699df06f45f7817bef9de37fc19fa620ae/practice_4/nodes/planning/global/lanelet2_global_planner.py#L25
3. `coordinate_transformer`, `use_custom_origin`, `utm_origin_lat` and `utm_origin_lon` are not the parameters of this method. They are the parameters of the entire `lanelet2_global_planner` node. We usually load all parameters that come from config or launch files inside the `__init__` method. I actually doubt if a separate method for loading lanelet2 map is even necessary. It's perfectly OK to do it in `__init__` method.
https://github.com/raunoraa/autoware_mini_practice_solutions/blob/9e1c00699df06f45f7817bef9de37fc19fa620ae/practice_4/nodes/planning/global/lanelet2_global_planner.py#L61-L70
4. Check that the speed limit is not negative and less than the default speed limit. It's good to have additional checks in the code as there can be mistakes on the lanelet2 map. 
    https://github.com/raunoraa/autoware_mini_practice_solutions/blob/9e1c00699df06f45f7817bef9de37fc19fa620ae/practice_4/nodes/planning/global/lanelet2_global_planner.py#L100-L103
5. You can just divide by `3.6` here. Makes the calculation a little more concise.
    https://github.com/raunoraa/autoware_mini_practice_solutions/blob/9e1c00699df06f45f7817bef9de37fc19fa620ae/practice_4/nodes/planning/global/lanelet2_global_planner.py#L105

**Comment by raunoraa** [comment]
Fixed the issues. 

As for the 3rd point, I thought it would be better to keep the function `load_lanelet2_map`, because then the `__init__` section would look more clean in my opinion. I just changed the parameters and docs of the `load_lanelet2_map`, because I moved getting the ros parameters from the map loading function to the `__init__` function.

**Comment by Karljohan99** [comment]
Additional comments:

1. Here you are loading parameters as local variables and giving them to a class method as variables. At the same time the method doesn't even use `self` inside of it. I would just load the parameters as class variables and access them with `self` in the method. An alternative approach is to make `load_lanelet2_map` as a helper function and move it outside of the class, but I would personally use just class variables. 
    https://github.com/raunoraa/autoware_mini_practice_solutions/blob/75c286d11e3e45b8fd3289a502e35d517d6e4a81/practice_4/nodes/planning/global/lanelet2_global_planner.py#L29-L42
2. You are again iterating over waypoints twice. It's actually possible to do the waypoint extraction with one iteration, but it can get quite complicated, so you don't have to implement it.
    https://github.com/raunoraa/autoware_mini_practice_solutions/blob/75c286d11e3e45b8fd3289a502e35d517d6e4a81/practice_4/nodes/planning/global/lanelet2_global_planner.py#L124
    https://github.com/raunoraa/autoware_mini_practice_solutions/blob/75c286d11e3e45b8fd3289a502e35d517d6e4a81/practice_4/nodes/planning/global/lanelet2_global_planner.py#L231
3. I doubt the need for this method. You are using it only at one place and it also doesn't use `self`, so it doesn't need to be a inside the class. Usually we just put these kind of functions to a separate helper file.
    https://github.com/raunoraa/autoware_mini_practice_solutions/blob/75c286d11e3e45b8fd3289a502e35d517d6e4a81/practice_4/nodes/planning/global/lanelet2_global_planner.py#L161-L162

**Comment by raunoraa** [comment]
Implemented the fixes.

**Comment by Karljohan99** [comment]
One tiny problem remains:

- The z-coordinate shouldn't be taken from the waypoint before the goal point as they can be quite far from each other. Think of the stretch of Riia street that goes up Riia Hill. It's straight, so the waypoints there might be tens of meters apart, but the elevation changes quickly. For a 20-30 meter stretch, the elevation difference might be greater than the vehicle's height. I recommend using linear interpolation here, which may not be exactly correct but is much closer to the actual elevation.
https://github.com/raunoraa/autoware_mini_practice_solutions/blob/fe477acac3d9dc26c8fd2a55565356ad554f487e/practice_4/nodes/planning/global/lanelet2_global_planner.py#L174-L175

You can close the issue after fixing this.
